# Generated by Django 6.0.2 on 2026-02-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lattes', models.URLField(verbose_name='Link do Lattes')),
                ('grande_area', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('ano', models.IntegerField()),
                ('link', models.URLField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='periodico.professor')),
            ],
        ),
    ]
