# Generated by Django 6.0.2 on 2026-02-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='aceitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='capitulos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='congresso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='livros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='periodico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='producao_biblio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='resumos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
