# Generated by Django 6.0.2 on 2026-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodico', '0002_professor_aceitos_professor_capitulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='aceitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='capitulos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='congresso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='livros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='periodico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='producao_biblio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='resumos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
