# Generated by Django 6.0.2 on 2026-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodico', '0003_alter_professor_aceitos_alter_professor_capitulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.TextField(),
        ),
    ]
