# Generated by Django 6.0.2 on 2026-02-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodico', '0004_alter_publicacao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='visualizacoes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
